Repository saltstack/salt-enhancement-proposals, pull requests merged in 2021-06, with the labels that each got.

#36 SEP 27: Create Community Advisory Board
  pull/0027_Create_Community_Advisory_Board
Labels: Abandoned

#46 SEP 31: Replace freenode references with liberachat.
  .github/config.yml
  accepted/0014-dev-overhaul.md
Labels: Draft

#34 SEP 26: Package Salt with Tiamat
  accepted/package-salt-with-tiamat.md
Labels: Final Comment Period
